### ISSUE TITLE
is this malware?

### ISSUE THREAD

**Issue by mxlouka** [Polarmods/DevX-Cracked#14]
or is it a false positive?

**Comment by egonaut** [comment]
Yes, it contains the AgentTesla RAT (Remote Access Trojan).

**Comment by xAstroBoy** [comment]
that's a false positive lol

**Comment by egonaut** [comment]
> that's a false positive lol


https://www.hybrid-analysis.com/sample/15a3534676d742c0949e3c0f9e7e2fe4cf34fcbe599fb83b17bafd6db7fbf256



"DevXUnityUnpackerRun.exe" is allocating memory with PAGE_GUARD access rights
"DevXUnityUnpackerRun.exe" sleeping for "1566804069" milliseconds
"DevXUnityUnpackerRun.exe" monitors "\REGISTRY\MACHINE\SOFTWARE\Microsoft\Ole" (Filter: 268435457; Subtree: 0)
"DevXUnityUnpackerRun.exe" monitors "\REGISTRY\USER\S-1-5-21-735145574-3570218355-1207367261-1001_Classes\Local Settings\Software\Microsoft" (Filter: 268435457; Subtree: 1)
"DevXUnityUnpackerRun.exe" monitors "\REGISTRY\USER\S-1-5-21-735145574-3570218355-1207367261-1001_Classes" (Filter: 268435461; Subtree: 1)
"DevXUnityUnpackerRun.exe" (Path: "HKLM\SOFTWARE\POLICIES\MICROSOFT\WINDOWS\SAFER\CODEIDENTIFIERS"; Key: "TRANSPARENTENABLED")

**Comment by marcussacana** [comment]
Your copied and past info have nothing dangerous at all.

**Comment by egonaut** [comment]
What I'm more concerned with is this:

"C:\Windows\system32\SearchProtocolHost.exe" Global\UsGthrFltPipeMssGthrPipe3_ Global\UsGthrCtrlFltPipeMssGthrPipe3 1 -2147483646 "Software\Microsoft\Windows Search" "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT; MS Search 4.0 Robot)" "C:\ProgramData\Microsoft\Search\Data\Temp\usgthrsvc" "DownLevelDaemon"

There shouldn't be any reason to touch/check the LSA protection, even in the context of a crack/DRM.

After running the .exe, there are 54 registry changes.

After running the .exe and waiting 65056ms, it calls for Global\SvcctrlStartEvent_A3752DX. 

This is used to duplicate Windows services. Searching that on google, it's really only seen in legitimate malware. 

It also messes around with a proxy function and reads the machines network connection information. I dunno.

I'm not an expert, so I'm not going to definitively say this is malicious. But, at the same time, I like to think I have at least a few brain cells and just after seeing all that this crack (or even program) touches, I'm gonna personally *not* run it on my main machine.

Run it in a sandbox or VM if you're paranoid like me. ¯\_(ツ)_/¯

**Comment by marcussacana** [comment]
I didn't feel the registry that suspect, but the 
`After running the .exe and waiting 65056ms, it calls for Global\SvcctrlStartEvent_A3752DX.`
is something that I can suspect, 
Whatever don't hurt anyone run in a VM, the crack it self works.

**Comment by Kiffolisk** [comment]
i think actual devx does that
