### ISSUE TITLE
Update DevXUnity to 11.09

### ISSUE THREAD

**Issue by DSwizzy** [Polarmods/DevX-Cracked#19]
There's been plenty of new updates that has been released for quite sometime nowadays, a new one 11.06 that just went released back February 20th of this year, any idea when you could update the crack for the newer versions please?

EDIT: 11.09 is the new update, so focus should go to that version now

**Comment by hanicraft** [comment]
yeah i dont know why they not update it

**Comment by Zensusy** [comment]
> yeah i dont know why they not update it

its hard to crack a software so be patient

**Comment by ke6DcAiCunUmK4l2YKsYKxVSB7vAiWMj6FCw2md** [comment]
Updated to 11.10
