### ISSUE TITLE
Not related to crack, but can't make demo license

### ISSUE THREAD

**Issue by lost3o** [Polarmods/DevX-Cracked#25]
Tried any email address that I had, none went through
![image](https://github.com/Polarmods/DevX-Cracked/assets/126967739/681cdad4-cfbd-4eb4-bdf4-368114a0b367)
So I can't really use the crack anyways, but maybe I'm doing something wrong?

**Comment by karlseven** [comment]
they are blacklisting IP so you wont be able to get a license. When you open the crack the first time
