### ISSUE TITLE
Exported dlls are empty

### ISSUE THREAD

**Issue by xAstroBoy** [Polarmods/DevX-Cracked#3]
It doesnt even generate a proper unity project and is exporting all the assemblies as empty dlls , when i would have loved to have those dlls being filled with code to analyze them with dnspy.

**Comment by hiyall360** [comment]
Message from cracker: Need crack version 1.0.3 at least for this - will be released to Public soon (has been private for PolarMods).

**Comment by xAstroBoy** [comment]
Ill reopen this as is not working on the newest version, all exported dlls are still empty methods 
@hiyall360

**Comment by hiyall360** [comment]
Shoot me a message on Discord and I'll look into it for you: hiyall360#7146
