### ISSUE TITLE
Torjan

### ISSUE THREAD

**Issue by w2lf** [Polarmods/DevX-Cracked#38]
Just be careful and run this in Windows Sandbox.

https://www.virustotal.com/gui/file/15a3534676d742c0949e3c0f9e7e2fe4cf34fcbe599fb83b17bafd6db7fbf256/detection
![image](https://github.com/Polarmods/DevX-Cracked/assets/37519962/895b9b28-a679-4ee7-9bb8-027221e90d7f)

**Comment by hiyall360** [comment]
False positive.

**Comment by w2lf** [comment]
> False positive.

still safer to run in Windows Sandbox

**Comment by TacoDark** [comment]
Its cracked, what the fuck do you expect?
Its gonna be a false positive
