### ISSUE TITLE
[Offtopic] Thanks

### ISSUE THREAD

**Issue by marcussacana** [Polarmods/DevX-Cracked#5]
I don't know who cracked, but I want to say thanks.
This is a big thing for the modding community :3 
When I can, I will try donate a bit to that BTC wallet, but not right now because i'm poor. (obvious, after all I don't have the DevX, lol)

**Comment by freMea** [comment]
Maybe but whaou. I would not run this outside of a sandbox.
https://www.virustotal.com/gui/file/15a3534676d742c0949e3c0f9e7e2fe4cf34fcbe599fb83b17bafd6db7fbf256/detection

![image](https://user-images.githubusercontent.com/22337329/199969581-c76400b0-0dd7-4e7c-952e-1fe23f72b868.png)

**Comment by xAstroBoy** [comment]
is a crack, and is possible that's false positives.

**Comment by marcussacana** [comment]
the devx protection itself is suspect to me.
But yes, I'm running in a VirutalMachine, (not because of suspect, but because I use Linux as main system)
And I don't think the cracker will give the trouble to crack a stronger protection like this one just to share a trojan, but whatever.

**Comment by ke6DcAiCunUmK4l2YKsYKxVSB7vAiWMj6FCw2md** [comment]
> Maybe but whaou. I would not run this outside of a sandbox. https://www.virustotal.com/gui/file/15a3534676d742c0949e3c0f9e7e2fe4cf34fcbe599fb83b17bafd6db7fbf256/detection
> 

This is due dnSpy. Original Run exe has 6 detentions. Idk how to fix this

**Comment by ke6DcAiCunUmK4l2YKsYKxVSB7vAiWMj6FCw2md** [comment]
> the devx protection itself is suspect to me. But yes, I'm running in a VirtualMachine, (not because of suspect, but because I use Linux as main system) And I don't think the cracker will give the trouble to crack a stronger protection like this one just to share a trojan, but whatever.

DevX doesn't have very strong protection.

**Comment by marcussacana** [comment]
If isn't strong and even with that they remain so much time without a crack

**Comment by xAstroBoy** [comment]
> If isn't strong and even with that they remain so much time without a crack
Because nobody knew where to look, this crack has been made using a real purchased version and from there they tracked all the activation steps devx is doing.

**Comment by ke6DcAiCunUmK4l2YKsYKxVSB7vAiWMj6FCw2md** [comment]
> > If isn't strong and even with that they remain so much time without a crack
> 
> Because nobody knew where to look, this crack has been made using a real purchased version and from there they tracked all the activation steps devx is doing.

Purchased version allow to activate some features. Without it working: il2cpp decompiler, shader decompiler and DevXC scripts. Other functions like repack can be activated, but it need many time to find method that start repack, And need full version of DevX because in demo part of code removed.

**Comment by marcussacana** [comment]
by the way, I tried decompile a shader here, and got just a broken script with some variables that don't exists, that's the usual or is because I used a game with unity version too high?
Unfortally I don't know how to create shaders, then I think I will need try create a dummy shader and replace the binary after build.

**Comment by ke6DcAiCunUmK4l2YKsYKxVSB7vAiWMj6FCw2md** [comment]
> by the way, I tried decompile a shader here, and got just a broken script with some variables that don't exists, that's the usual or is because I used a game with unity version too high? Unfortally I don't know how to create shaders, then I think I will need try create a dummy shader and replace the binary after build.

I tried shader decompile in unity 2018, same result. It always gen broken shaders. I was able to fix but they only work fine in Unity Editor. Need wait when DevX update shader decompiler

**Comment by marcussacana** [comment]
I see, or I may try do the correct thing and study, lol... who know when the DevX will fix it...

**Comment by freMea** [comment]
> > Maybe but whaou. I would not run this outside of a sandbox. https://www.virustotal.com/gui/file/15a3534676d742c0949e3c0f9e7e2fe4cf34fcbe599fb83b17bafd6db7fbf256/detection
> 
> This is due dnSpy. Original Run exe has 6 detentions. Idk how to fix this

I use [dnSpyEx](https://github.com/dnSpyEx) and no issue with virus detection.
![image](https://user-images.githubusercontent.com/22337329/200209845-de20d558-fa5e-4643-8bca-c3a20a84d205.png)

**Comment by marcussacana** [comment]
maybe because invalid exe signature it was flagged?
Well, if the original executable already is flagged there's nothing that can be done.

**Comment by ke6DcAiCunUmK4l2YKsYKxVSB7vAiWMj6FCw2md** [comment]
> 

I use it too so idk why detections on VT
