### ISSUE TITLE
[Request] Game Extractor

### ISSUE THREAD

**Issue by 10522** [Polarmods/DevX-Cracked#8]
Is it possible to crack the latest version of [Game Extractor](http://www.watto.org/game_extractor.html)?

Game Extractor supports thousands of games, including Unity games.

**Comment by ke6DcAiCunUmK4l2YKsYKxVSB7vAiWMj6FCw2md** [comment]
Just download source, in org/watto/ge/GameExtractor.java find 
```java
public static boolean isFullVersion() {
    try {
      new FullVersionVerifier();
      return true;
    }
    catch (Throwable t) {
      return false;
    }
  }
```
And replace to
```java
public static boolean isFullVersion() {
      return true;
  }
```
Then just build.
Source are here [SourceForge](https://sourceforge.net/projects/gameextractor/files/Game%20Extractor%203.0x/3.14/)
If u can't do this. Cracked version for u [Game Extractor.zip](https://github.com/Polarmods/DevX-Cracked/files/9994115/Game.Extractor.zip)

**Comment by ke6DcAiCunUmK4l2YKsYKxVSB7vAiWMj6FCw2md** [comment]
Maybe
