### ISSUE TITLE
[Offtopic] Updating to v11

### ISSUE THREAD

**Issue by Manurocker95** [Polarmods/DevX-Cracked#9]
Any ETA or possibility to update it to v11.01?

**Comment by ke6DcAiCunUmK4l2YKsYKxVSB7vAiWMj6FCw2md** [comment]
There will be an update.

**Comment by Manurocker95** [comment]
> There will be an update.

Any ETA?

**Comment by xAstroBoy** [comment]
> > There will be an update.
> 
> Any ETA?

don't push.

**Comment by tracer8** [comment]
> There will be an update.

Now demo version must have license to download it, if you want, i can send you an setup i have for last one.

**Comment by Manurocker95** [comment]
> > There will be an update.
> 
> Now demo version must have license to download it, if you want, i can send you an setup i have for last one.

11.02?

**Comment by tracer8** [comment]
> > > There will be an update.
> > 
> > 
> > Now demo version must have license to download it, if you want, i can send you an setup i have for last one.
> 
> 11.02? release or demo?

Demo, my license have been expired for update.

**Comment by Manurocker95** [comment]
> > > > There will be an update.
> 
> > > 
> 
> > > 
> 
> > > Now demo version must have license to download it, if you want, i can send you an setup i have for last one.
> 
> > 
> 
> > 11.02? release or demo?
> 
> 
> 
> Demo, my license have been expired for update.

Requesting the demo is simple and free (takes a few mins) but you can't use your license on it like you could before so I guess now they are completely different versions

**Comment by xAstroBoy** [comment]
news?

**Comment by jimmmmmmmmmyfunnnnnnny** [comment]
news?

**Comment by tracer8** [comment]
Look like DevX author hire a hitman to hunt him down. 🥲

**Comment by marcussacana** [comment]
we have to make a crowdfunding and pay twice as much for the killer to abandon the target.

**Comment by ke6DcAiCunUmK4l2YKsYKxVSB7vAiWMj6FCw2md** [comment]
11.09 WIP

**Comment by marcussacana** [comment]
@ke6DcAiCunUmK4l2YKsYKxVSB7vAiWMj6FCw2md I just think in this now, but if this repo is takedown one day where should be a secondary trustable source for your cracks?

**Comment by ke6DcAiCunUmK4l2YKsYKxVSB7vAiWMj6FCw2md** [comment]
Updated to 11.10
